### ISSUE TITLE
404 Client Error: Not Found for url:

### ISSUE THREAD

**Issue by aquilano76** [jasonrollins/shareplum#127]
Hi, calling Site method on a library [site = Site('http://mysharepoint/sistemi/provaAndrea/testAndrea/Test', version=Version.v2013, auth=cred)] results in the following error.

The page http://mysharepoint/sistemi/provaAndrea/testAndrea/Test/_vti_bin/Sites.asmx responds well.

Could you help me?
Thank you, kind regards
Andrea

Traceback (most recent call last):
  File "<pyshell#124>", line 1, in <module>
    site2 = Site('http://mysharepoint/sistemi/provaAndrea/testAndrea/Test', version=Version.v2013, auth=cred)
  File "c:\users\en21322\documents\python program\shareplum\shareplum\site.py", line 547, in Site
    ssl_version,
  File "c:\users\en21322\documents\python program\shareplum\shareplum\site.py", line 413, in __init__
    self.version = "v365"
  File "c:\users\en21322\documents\python program\shareplum\shareplum\site.py", line 95, in __init__
    self.site_info = self.get_site()
  File "c:\users\en21322\documents\python program\shareplum\shareplum\site.py", line 227, in get_site
    response = post(self._session,
  File "c:\users\en21322\documents\python program\shareplum\shareplum\request_helper.py", line 20, in post
    raise ShareplumRequestError("Shareplum HTTP Post Failed", err)
shareplum.errors.ShareplumRequestError: Shareplum HTTP Post Failed : **404 Client Error: Not Found for url: http://mysharepoint/sistemi/provaAndrea/testAndrea/Test/_vti_bin/Sites.asmx**

**Comment by jasonrollins** [comment]
This does not look like a valid url to me.  Is this a link to a local file
on your computer?

**Comment by aquilano76** [comment]
Hi Jason, thank you for your reply.
It is a company intranet site.

I couldn't realize why the POST call fails with that error.
How could get a better error explaination?

Thank you,
Andrea

________________________________
Da: Jason Rollins <notifications@github.com>
Inviato: giovedì 8 ottobre 2020 04:28
A: jasonrollins/shareplum <shareplum@noreply.github.com>
Cc: aquilano76 <andy_p76@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [jasonrollins/shareplum] 404 Client Error: Not Found for url: (#127)


This does not look like a valid url to me. Is this a link to a local file
on your computer?
