### ISSUE TITLE
IndexError during UpdateListItems

### ISSUE THREAD

**Issue by Ghandi263** [jasonrollins/shareplum#14]
I've written a program to  completely clear a SharePoint list of it's data. Since my real project is in the development phase, this allows me to easily clear it if I mess something up and try again. My program to clear the data looks like this:

```
from my_stuff import get_auth
from requests_ntlm import HttpNtlmAuth
from shareplum import Site

user, pw = get_auth()

sp_auth = HttpNtlmAuth(f'domain\\{user}', pw)
url = 'http://web.site.com/path/to/site'
site = Site(url, sp_auth)
dev_list = site.List('App_Dev')

dev_ids = [row['ID'] for row in dev_list.GetListItems(fields=['ID'])]

dev_list.UpdateListItems(dev_ids, 'Delete')
```

This worked fine before, but somewhat suddenly started throwing an `IndexError` earlier today. Stack trace:

```
Traceback (most recent call last):
  File "C:/Path/to/folder/clear_sp.py", line 16, in <module>
    dev_list.UpdateListItems(dev_ids, 'Delete')
  File "C:\Path\to\Python\Python36\lib\site-packages\shareplum\shareplum.py", line 559, in UpdateListItems
    results = envelope[0][0][0][0]
  File "src\lxml\lxml.etree.pyx", line 1178, in lxml.etree._Element.__getitem__ (src\lxml\lxml.etree.c:55127)
IndexError: list index out of range
```

**Comment by jasonrollins** [comment]
Sorry, I'm going to close this for now.  Please open another issue, if you can still reproduce the failure.
