### ISSUE TITLE
Shareplum HTTP Post Failed

### ISSUE THREAD

**Issue by qq670123124** [jasonrollins/shareplum#147]
I always get an error when I try to insert more than 500 records

Traceback (most recent call last):
  File "D:\Python\lib\site-packages\shareplum\request_helper.py", line 17, in post
    response.raise_for_status()
  File "D:\Python\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://test-spapp1:8002/_vti_bin/lists.asmx

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/code/untitled/sp_kjfwy.py", line 57, in <module>
    share(df)
  File "E:/code/untitled/sp_kjfwy.py", line 31, in share
    sp_list.UpdateListItems(data=ans_list, kind='New')
  File "D:\Python\lib\site-packages\shareplum\list.py", line 457, in update_list_items
    response = post(self._session,url=self._url("Lists"),headers=self._headers("UpdateListItems"),data=str(soap_request).encode("utf-8"),verify=self._verify_ssl,timeout=self.timeout)
  File "D:\Python\lib\site-packages\shareplum\request_helper.py", line 20, in post
    raise ShareplumRequestError("Shareplum HTTP Post Failed", err)
shareplum.errors.ShareplumRequestError: Shareplum HTTP Post Failed : 500 Server Error: Internal Server Error for url: http://test-spapp1:8002/_vti_bin/lists.asmx

**Comment by jasonrollins** [comment]
Is it possibly a limitation imposed by your server?  There is a known issue of trying to getting and setting more than 5000 rows.  Do you get the error if you insert 499 records?  Is it exactly 500 that's causing you issues?
