### ISSUE TITLE
TypeError on DESCENDING order

### ISSUE THREAD

**Issue by atomheart** [jasonrollins/shareplum#18]
It is impossible to use descending order, because there is TypeError in code:

```
Traceback (most recent call last):
  File "test\sp_test_02.py", line 30, in <module>
    query=query
  File "env\lib\site-packages\shareplum\shareplum.py", line 382, in GetListItems
    soap_request.add_query(query)
  File "env\lib\site-packages\shareplum\shareplum.py", line 675, in add_query
    fieldref.set('Name', field)
  File "src\lxml\etree.pyx", line 826, in lxml.etree._Element.set (src\lxml\etree.c:52969)
  File "src\lxml\apihelpers.pxi", line 575, in lxml.etree._setAttributeValue (src\lxml\etree.c:24306)
  File "src\lxml\apihelpers.pxi", line 1442, in lxml.etree._utf8 (src\lxml\etree.c:32904)
TypeError: Argument must be bytes or unicode, got 'tuple'
```

Error is occures in shareplum.py code:

```python
                # HERE you first try try to add field
                fieldref.set('Name', field)
                # AND THEN you check field type
                if type(field) == tuple:
                    fieldref.set('Name', field[0])
                    if field[1] == 'DESCENDING':
                        fieldref.set('Ascending', 'FALSE')
```

Must be like this:

```python
                if type(field) == tuple:
                    fieldref.set('Name', field[0])
                    if field[1] == 'DESCENDING':
                        fieldref.set('Ascending', 'FALSE')
                else:
	                fieldref.set('Name', field)
```

Please, fix it.

**Comment by jasonrollins** [comment]
Do you want to send me a pull request or just change it on my end?

**Comment by atomheart** [comment]
Please change it yourself.
