### ISSUE TITLE
XMLSyntaxError when attempting to call GetListItems("All Items") on large list

### ISSUE THREAD

**Issue by jamesmcm** [jasonrollins/shareplum#51]
The following code fails:

```python
from shareplum import Site
from requests_ntlm import HttpNtlmAuth

auth = HttpNtlmAuth('user', 'pass')
site = Site('https://share.site.com/sites/sharepoint', auth=auth, verify_ssl=False)
sp_list = site.List('List Name')
data = sp_list.GetListItems('All Items')
```

With this error:

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-8-0437fa9bc6e2>", line 7, in <module>
    data = sp_list.GetListItems('All Items')

  File "/usr/local/lib/python3.7/site-packages/shareplum/shareplum.py", line 494, in GetListItems
    envelope = etree.fromstring(response.text.encode('utf-8'), parser=etree.XMLParser(huge_tree=self.huge_tree))

  File "src/lxml/etree.pyx", line 3234, in lxml.etree.fromstring

  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument

  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDoc

  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc

  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc

  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult

  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError

  File "<string>", line 16175
XMLSyntaxError: internal error: Huge input lookup, line 16175, column 989
```

But it works if I only request 1000 rows, how should I get all the data?

**Comment by jamesmcm** [comment]
Fixed by using huge_tree=True:

```python
site = Site('https://share.site.com/sites/sharepoint', auth=auth, verify_ssl=False, huge_tree=True)
```
