### ISSUE TITLE
Huge input lookup, line 14046, column 451

### ISSUE THREAD

**Issue by Daemon2017** [jasonrollins/shareplum#60]
Hello!

I wrote the code and it perfect works on my PC (Win7, Python 3.6.1), but on Jenkins (Linux, Python 3.4) I'm getting an error:

```
Traceback (most recent call last):
  File "to_ift.py", line 24, in <module>
    site = Site('http://sbt-dk/sites/PIR/', auth=auth)
  File "/u01/jenkins_slave/workspace/imod/oku/ift/lib/python3.4/site-packages/shareplum/shareplum.py", line 128, in __init__
    self.users = self.GetUsers()
  File "/u01/jenkins_slave/workspace/imod/oku/ift/lib/python3.4/site-packages/shareplum/shareplum.py", line 281, in GetUsers
    envelope = etree.fromstring(response.text.encode('utf-8'), parser=etree.XMLParser(huge_tree=self.huge_tree))
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1126, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 600, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 710, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 639, in lxml.etree._raiseParseError
  File "<string>", line 14046
lxml.etree.XMLSyntaxError: internal error: Huge input lookup, line 14046, column 451
Build step 'Execute shell' marked build as failure
```

I've installed dependencies like this (both locally and in Jenkins):
```
+ python3 -m pip install requests==2.21.0 --index-url=http://sbtnexus.ca.sbrf.ru:8081/nexus/content/repositories/OAIR_tool_release/pypi/simple/ --trusted-host=sbtnexus.ca.sbrf.ru
Requirement already satisfied: requests==2.21.0 in ./ift/lib/python3.4/site-packages
Requirement already satisfied: idna<2.9,>=2.5 in ./ift/lib/python3.4/site-packages (from requests==2.21.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./ift/lib/python3.4/site-packages (from requests==2.21.0)
Requirement already satisfied: certifi>=2017.4.17 in ./ift/lib/python3.4/site-packages (from requests==2.21.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./ift/lib/python3.4/site-packages (from requests==2.21.0)
+ python3 -m pip install SharePlum --index-url=http://sbtnexus.ca.sbrf.ru:8081/nexus/content/repositories/OAIR_tool_release/pypi/simple/ --trusted-host=sbtnexus.ca.sbrf.ru
Requirement already satisfied: SharePlum in ./ift/lib/python3.4/site-packages
Requirement already satisfied: requests-ntlm in ./ift/lib/python3.4/site-packages (from SharePlum)
Requirement already satisfied: lxml in ./ift/lib/python3.4/site-packages (from SharePlum)
Requirement already satisfied: requests in ./ift/lib/python3.4/site-packages (from SharePlum)
Requirement already satisfied: requests-toolbelt in ./ift/lib/python3.4/site-packages (from SharePlum)
Requirement already satisfied: ntlm-auth>=1.0.2 in ./ift/lib/python3.4/site-packages (from requests-ntlm->SharePlum)
Requirement already satisfied: cryptography>=1.3 in ./ift/lib/python3.4/site-packages (from requests-ntlm->SharePlum)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./ift/lib/python3.4/site-packages (from requests->SharePlum)
Requirement already satisfied: idna<2.9,>=2.5 in ./ift/lib/python3.4/site-packages (from requests->SharePlum)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./ift/lib/python3.4/site-packages (from requests->SharePlum)
Requirement already satisfied: certifi>=2017.4.17 in ./ift/lib/python3.4/site-packages (from requests->SharePlum)
Requirement already satisfied: six>=1.4.1 in ./ift/lib/python3.4/site-packages (from cryptography>=1.3->requests-ntlm->SharePlum)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in ./ift/lib/python3.4/site-packages (from cryptography>=1.3->requests-ntlm->SharePlum)
Requirement already satisfied: asn1crypto>=0.21.0 in ./ift/lib/python3.4/site-packages (from cryptography>=1.3->requests-ntlm->SharePlum)
Requirement already satisfied: pycparser in ./ift/lib/python3.4/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=1.3->requests-ntlm->SharePlum)
```

What could I do wrong?

**Comment by jasonrollins** [comment]
Can you confirm if this is for a newer SharePoint? 2016 or greater?  I'd like to move all issues for newer versions of SharePoint to SharePlum2.

**Comment by jasonrollins** [comment]
There is a huge_tree option in Site:
`Site(huge_tree=True)`
Try that and see if that resolves your issue.

**Comment by Daemon2017** [comment]
Hello, jasonrollins. I'm using SharePoint Server 2013.
Thank you for reply - I'll try to with that option.
