### ISSUE TITLE
Index Out of Range

### ISSUE THREAD

**Issue by karthik-tableau** [jasonrollins/shareplum#64]
from shareplum import Site
from requests_ntlm import HttpNtlmAuth
import pandas as pd
import datetime

#***********************Login into SharePoint Site***************************#
auth = HttpNtlmAuth('xxxx', 'xxxxx')
site = Site('https://x.x.com/sites/UnityI/xx', auth=auth,huge_tree=True)

sp_list = site.List('Investment Request')
approved_data = sp_list.GetListItems(viewname='All Condensed',query=None)
df = pd.DataFrame(approved_data)

# ***********************Read List2 Data - UnApproved List********************#

sp_list = site.List('Investment Request UnApproved')
unapproved_data = sp_list.GetListItems(viewname='All Unapproved Projects',query=None)
df1 = pd.DataFrame(unapproved_data)

#
# #*****************Concatenate - Approved & UnApproved List********************#
#
df2 = pd.concat([df,df1], ignore_index=True, sort=False)
CombinedData = pd.DataFrame(df2)

CombinedData_3Columns = pd.DataFrame(CombinedData, columns=['ID','Project Name Title','Project Type','Client','Approval','Approval Date','Est Cost'])

CombinedData_3Columns = CombinedData_3Columns.astype(str)

new_list = site.List('IRC Combined Data')
fields = ['ID']
dev_ids =  [row['ID'] for row in new_list.GetListItems(fields=fields)]
new_list.UpdateListItems(dev_ids, 'Delete')

new_list = site.List('IRC Combined Data')
my_data=data= approved_data_todict
new_list.UpdateListItems(data=my_data, kind='New')

Once i run the above script, I am getting below the error message.

Traceback (most recent call last):
  File "C:/PyCharm/CombinedData.py", line 64, in <module>
    new_list.UpdateListItems(data=my_data, kind='New')
  File "C:\Python\lib\site-packages\shareplum\shareplum.py", line 658, in UpdateListItems
    envelope = etree.fromstring(response.text.encode('utf-8'), parser=etree.XMLParser(huge_tree=self.huge_tree))
  File "src\lxml\etree.pyx", line 3236, in lxml.etree.fromstring
  File "src\lxml\parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src\lxml\parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src\lxml\parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src\lxml\parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 11
lxml.etree.XMLSyntaxError: expected '>', line 11, column 112

**Comment by jasonrollins** [comment]
Can you confirm if this is for a newer SharePoint? 2016 or greater?  I'd like to move all issues for newer versions of SharePoint to SharePlum2.

**Comment by jasonrollins** [comment]
Can you tell me more about what is in "approved_data_todict"?

**Comment by karthik-tableau** [comment]
C:\Python\python.exe C:/PyCharm/CombinedData.py
ID                    object
Project Name Title            object
Project Type                  object
Client                        object
Approval                  object
Approval Date     datetime64[ns]
Est Cost                     float64
dtype: object

**Comment by karthik-tableau** [comment]
it contains 3000 list of dictionary data which i can't share here as it has sensitive data.

**Comment by karthik-tableau** [comment]
> Can you confirm if this is for a newer SharePoint? 2016 or greater? I'd like to move all issues for newer versions of SharePoint to SharePlum2.

how to check this?
