### ISSUE TITLE
Exception: Can't get User Info List

### ISSUE THREAD

**Issue by rdhar8502** [jasonrollins/shareplum#69]
MyCode:
from shareplum import Site
from requests_ntlm import HttpNtlmAuth

auth = HttpNtlmAuth("domain\\user", "pass1234")

site = Site('http://sp.example.com/production/Client/NewSite_Template2', auth=auth)

sp_list = site.Lists('Shared Documents')

data = sp_list.GetListItems('All Items')

Error:
Traceback (most recent call last):
  File "C:/Users/rahul.dhar/Desktop/sharepoin.py", line 9, in <module>
    site = Site('http://sp.alliancetek.com/production/Client/NewSite_Template2', auth=auth)
  File "C:\Users\rahul.dhar\AppData\Local\Programs\Python\Python36\lib\site-packages\shareplum\shareplum.py", line 128, in __init__
    self.users = self.GetUsers()
  File "C:\Users\rahul.dhar\AppData\Local\Programs\Python\Python36\lib\site-packages\shareplum\shareplum.py", line 291, in GetUsers
    raise Exception("Can't get User Info List")
Exception: Can't get User Info List

**Comment by jasonrollins** [comment]
User info is the first thing the library tries to retrieve.  It fails if
your authentication is incorrect.
