### ISSUE TITLE
syntaxError while import

### ISSUE THREAD

**Issue by likhithn** [jasonrollins/shareplum#73]
While making an old code compatible for python3 I got the error below
Traceback (most recent call last):
  File "/home/likhithn/pmt_scripts/sandysi/create_rns/rn.py", line 33, in <module>
    from shareplum import Site
  File "/home/likhithn/.local/lib/python3.5/site-packages/shareplum/__init__.py", line 6, in <module>
    from .site import Site  # noqa: F401
  File "/home/likhithn/.local/lib/python3.5/site-packages/shareplum/site.py", line 12, in <module>
    from .list import _List2007, _List365
  File "/home/likhithn/.local/lib/python3.5/site-packages/shareplum/list.py", line 547
    url = self.site_url + f"/_api/lists/getbytitle('{self.list_name}')/RenderListDataAsStream"
                                                                                             ^
SyntaxError: invalid syntax

What could be the reason for the failure?

**Comment by wannli** [comment]
Same issue here.

**Comment by jasonrollins** [comment]
What is your import statement and what python version are you using?

**Comment by likhithn** [comment]
from shareplum import site
Was using python2 but since it's deprecating, needed it to be compatible with python 3 as well

**Comment by jasonrollins** [comment]
I'm not sure why you are seeing this problem.  Can you assure you have the latest version?

**Comment by likhithn** [comment]
I am using o
Python v3.5 but the code worked fine in v2.7

**Comment by jasonrollins** [comment]
If you pip install shareplum --upgrade, do you still see the issue?

**Comment by losistefano** [comment]
Same issue here with Python v3.5 !!

**Comment by likhithn** [comment]
It exits even after 
$ pip3 install shareplum --upgrade

**Comment by SpiritQuaddicted** [comment]
Shareplum requires Python 3.6+, it does not support Python 3.5.

Python 3.5 is in end-of-life, it will not receive ANY updates starting next month, not even for security issues. Do not use Python 3.5 anymore. Update and you can enjoy shareplum.
