### ISSUE TITLE
Error authenticating against Office 365. Error from Office 365:

### ISSUE THREAD

**Issue by odairvaz** [jasonrollins/shareplum#84]
Hello everyone, 
I'm trying to upload some files to SharePoint in Office 365 but the authentication fails even  though that I put the right credentials.Here's the code.

`
from shareplum import Site
from shareplum import Office365
from shareplum.site import Version

#get all the csv files
csv_files = list(filter(lambda x: '.csv' in x, os.listdir('./csvfiles')))

# Office 365 Authentication
authcookie = Office365('https://tenant.sharepoint.com',
                       username='login@tenant.com', password='password').GetCookies()
site = Site('https://tenant.sharepoint.com/sites/Folder',
            version=Version.v365, authcookie=authcookie)
`
However, I do manage to log in and upload data with my personal account, but I can’t upload data with my organizational account
Here’s the message error when I try to log with my organizational account:
```
raise Exception('Error authenticating against Office 365. Error from Office 365:', message[0].text)
Exception: ('Error authenticating against Office 365. Error from Office 365:', 'AADSTS50126: Error validating credentials due to invalid username or password.')
```
Is there any way to fix it?

Thanks in advance

**Comment by jasonrollins** [comment]
Do you have any strange characters in your user name or password?  The Office365 authentication user xml.sax.saxutils.escape() to clean up special characters, but maybe it is interfering?

**Comment by jasonrollins** [comment]
Do you have any special characters in your username and password?

**Comment by vennamanand1** [comment]
I'm having the same issue, and no special characters are observed in my username and password. Can you please help?

**Comment by jasonrollins** [comment]
Can you try version 0.4.5 and see if that one works?

**Comment by vennamanand1** [comment]
Tried with 0.4.5 and the error is still the same.

**Comment by vennamanand1** [comment]
please help

**Comment by jasonrollins** [comment]
Try setting verify_ssl=False in your site object. Site(verify_ssl=False)

**Comment by odairvaz** [comment]
> Do you have any strange characters in your user name or password? The Office365 authentication user xml.sax.saxutils.escape() to clean up special characters, but maybe it is interfering?

no, my password and username doesn't have stange characters

**Comment by odairvaz** [comment]
I changed my code but i'm still having the same issue

```
from shareplum import Site
from shareplum import Office365
from shareplum.site import Version

#get all the csv files
csv_files = list(filter(lambda x: '.csv' in x, os.listdir('./csvfiles')))

# Office 365 Authentication
authcookie = Office365('https://tenant.sharepoint.com',
                       username='login@tenant.com', password='password').GetCookies()
site = Site('https://tenant.sharepoint.com/sites/Folder',
            version=Version.v365, authcookie=authcookie, verify_ssl=False)
```
But i keep having the same error
```
Traceback (most recent call last):
  File "rest-api.py", line 19, in <module>
    authcookie = Office365('https://tenant.sharepoint.com',
  File "C:\Users\username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\shareplum\office365.py", line 87, in get_cookies
    sectoken = self.get_security_token(self.username, self.password)
  File "C:\Users\username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\shareplum\office365.py", line 79, in get_security_token
    raise Exception('Error authenticating against Office 365. Error from Office 365:', message[0].text)
Exception: ('Error authenticating against Office 365. Error from Office 365:', 'AADSTS50126: Error validating credentials due to invalid username or password.')
```

**Comment by kmahanna** [comment]
I'm having a similar issue

```
from shareplum import Site
from shareplum import Office365
from shareplum.site import Version

authcookie = Office365('https://abc.sharepoint.com', username=username, password=password).GetCookies()
site = Site('https://abc.sharepoint.com/sites/MySharePointSite/', version=Version.v365, authcookie=authcookie)
```
with this error:
```
Exception: ('Error authenticating against Office 365. Was not able to find an error code. Here is the SOAP response from Office 365'
```
It appears it can't get a security token.

**Comment by amanmajeed** [comment]
I am also facing a similar issue.

My code.
`
from shareplum import Site
from shareplum import Office365
from shareplum.site import Version

authcookie = Office365('https://***.sharepoint.com/', username='***', password='***').GetCookies()
site = Site('https://***.sharepoint.com/sites/Folder/', version=Version.v2016, authcookie=authcookie)
folder = site.Folder('Shared Documents/ME/')
folder.get_file('xyz.xlsx')
`
The error I am facing.
`
File "***\shareplum\office365.py", line 80, in get_security_token
    raise Exception('Error authenticating against Office 365. Error from Office 365:', message[0].text)
Exception: ('Error authenticating against Office 365. Error from Office 365:', "AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access ''.")
`

**Comment by odairvaz** [comment]
@jasonrollins can you help us with this issue, do you have any other suggestion ? thanks

**Comment by kmahanna** [comment]
I was able to use this work around to pull data from the file I needed with requests_ntlm. I really want to download the original file.

   ```
from requests_ntlm import HttpNtlmAuth
import requests
import os
from io import BytesIO
 
auth = HttpNtlmAuth(username = os.environ['user'],
                        password = os.environ['password'])
    
responseObject = requests.get(url, auth = auth)

file = BytesIO(responseObject.content)
df = pd.read_excel(file)
```

**Comment by Pear1125** [comment]
I also had this error

raise Exception('Error authenticating against Office 365. Error from Office 365:', message[0].text)
Exception: ('Error authenticating against Office 365. Error from Office 365:', 'AADSTS50126: Error validating credentials due to invalid username or password.')

@jasonrollins It would be great if you can help us here.

**Comment by nmduarte** [comment]
Hi all,

Facing this error too - 'Error authenticating against Office 365. Error from Office 365:', 'AADSTS50126: Error validating credentials due to invalid username or password.'

Credentials works just fine if I try to login directly into SP or if I use my company email. But using the service account email, I can't pass that error.

Any help would be appreciated.

**Comment by jasonrollins** [comment]
Apologies.  I'm not really sure how to debug logins.  Some people have
issues with their sites and some don't.  I only have access to a personal
Office 365 sharepoint site so I'm limited by what I can test.

**Comment by divy-works** [comment]
@jasonrollins The issues seems to be because of multi-factor authentication(such as okta) implemented on Office 365. I believe you are not facing this issue since your Office 365 has single-point authentication.

**Comment by BrandonMFong** [comment]
So I guess the question is how do we account for multi-factor authentication?

**Comment by divy-works** [comment]
> So I guess the question is how do we account for multi-factor authentication?

I vote for closing this issue. Multi-factor authentication has been created to prevent automated login. If someone wants to automate data storage in SharePoint then they should ask IT Team yo create exception for the login account. Trying to solve multi-factor authentication could be out of scope of your work.

**Comment by ahmedbrh** [comment]
Got the same error 
`Traceback (most recent call last):
  File "c:\VScode worksapce\SharePoint Script\project.py", line 8, in <module>
    SharePoint().upload_file(file_dir_path,file_name , folder_name)
  File "c:\VScode worksapce\SharePoint Script\sharepoint.py", line 42, in upload_file
    self._folder =   self.connect_folder(folder_name) 
  File "c:\VScode worksapce\SharePoint Script\sharepoint.py", line 35, in connect_folder
    self.auth_site = self.auth()
  File "c:\VScode worksapce\SharePoint Script\sharepoint.py", line 28, in auth
    self.authcookie = Office365(SHAREPOINT_URL , username = USERNAME , password =  PASSWORD).GetCookies()
  File "C:\Devtools\Install\Python\3.6.8-64-with-libs_rev2\lib\site-packages\shareplum\office365.py", line 88, in get_cookies
    sectoken = self.get_security_token(self.username, self.password)
  File "C:\Devtools\Install\Python\3.6.8-64-with-libs_rev2\lib\site-packages\shareplum\office365.py", line 80, in get_security_token
    raise Exception('Error authenticating against Office 365. Error from Office 365:', message[0].text)
Exception: ('Error authenticating against Office 365. Error from Office 365:', 'AADSTS50126: Error validating credentials due to invalid username or password.')

`


is there is anyone find the solution of this error auth please !

**Comment by black-syphilis** [comment]
`Exception: ('Error authenticating against Office 365. Error from Office 365:', 'AADSTS50034: The user account {EmailHidden} does not exist in the gmail.com directory. To sign into this application, the account must be added to the directory.')`

Same problem and I confirm there isn't multi-factor authentification

**Comment by FableWu** [comment]
> `Exception: ('Error authenticating against Office 365. Error from Office 365:', 'AADSTS50034: The user account {EmailHidden} does not exist in the gmail.com directory. To sign into this application, the account must be added to the directory.')`
> 
> Same problem and I confirm there isn't multi-factor authentification

Same issue to me.

**Comment by gezirong** [comment]
Hello, guys, anyone can solve this issue? I also facing this issue:

raise Exception('Error authenticating against Office 365. Error from Office 365:', message[0].text)
Exception: ('Error authenticating against Office 365. Error from Office 365:', 'AADSTS90023: Invalid STS request.')

**Comment by CodePidgy** [comment]
So is there just no way to use SharePlum on a SharePoint site that requires MFA? Is there no way to call the prompt to ask the user to login using MFA?

**Comment by xingfengf21** [comment]
This is my code. Who can solve this problem

from shareplum import Site
from shareplum import Office365
from shareplum.site import Version


# Office 365 Authentication
authcookie = Office365('https://xxxx.sharepoint.com/',
                       username='xxxx@fengx.onmicrosoft.com', password='xxxxxxxx').GetCookies()

print(authcookie)
site = Site('https://xxxxx.sharepoint.com/sites/site2',
            version=Version.v365, authcookie=authcookie, verify_ssl=False)



dir = 'Shared Documents\\test'
f = site.Folder(dir)

for file in f.files:
    print('--------')
    print(file)
    d = f.get_file(file['Name'])
    print(d)


for folder in f.folders:
    print(folder)

**Comment by bikashh1207** [comment]
I am getting the same error, anyone has any solution?

**Comment by manoharkakumani** [comment]
> 

Even I'm facing Exception: ('Error authenticating against Office 365. Was not able to find an error code. Here is the SOAP response from Office 365.

is there any solution?

**Comment by ranjith590** [comment]
same error for me too... but not progressive way on that...

**Comment by shivshankarpandit** [comment]
I am getting the same error pls hep me on this. Thanks

**Comment by ramvoci** [comment]
Stuck with the same issue and looking for a solution..  Thanks..

**Comment by elohbeck87** [comment]
same issue here as well.  IT said they will not remove MFA either.  Has anyone found a different library?

**Comment by todorpeshin** [comment]
Its not MFA issue I did test with users with MFA on/OFF on different site/tenant and it pass but on my organization it failing.

**Comment by elohbeck87** [comment]
I was able to get around the issue by using Office365-REST-Python-Client and creating a registered app with read-write permissions.

**Comment by mysticaljhb36** [comment]
> 

Amazing ! Could you share how you resolved the problem? I'm having similar issue due to multi-factor authentication. Thanks.

**Comment by elohbeck87** [comment]
This works well for me:

```
# we first need to register an app on the sharepoint site
# the app needs to have read-write permissions on the site
# install Office365-REST-Python-Client on the cluster

from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.sharepoint.client_context import ClientContext

# define sharepoint site url
baseurl = sp_url
basesite = '/sites/{}'.format(sp_site_name)
siteurl = baseurl + basesite 

# get client credentials from secrets
username = sp_app_client_id
password = sp_app_client_secret

# authenticate with sharepoint site
ctx_auth = AuthenticationContext(siteurl)
ctx_auth.acquire_token_for_app(username, password)
ctx = ClientContext(siteurl, ctx_auth)
```

**Comment by mysticaljhb36** [comment]
> xt(siteurl

Thanks a lot. This looks workable using the app auth (using service principal ID) rather than user auth method to bypass the MFA. :)
